Peripli/service-manager-cli

.gitignore, internal/cmd/commander.go, internal/cmd/login/login.go, internal/cmd/login/login_test.go, internal/configuration/configuration.go, pkg/auth/oidc/common.go, pkg/auth/oidc/oidc.go, pkg/auth/strategy.go, pkg/smclient/client.go, pkg/smclient/client_test.go, pkg/types/info.go
Some authorization servers like CF UAA have issues when client credentials are passed as basic auth.
See https://github.com/cloudfoundry/uaa/issues/778
SM can return on the info endpoint a new property token_basic_auth (default true).
If token_basic_auth is false, client credentials are sent in the body instead of in authorization header (basic auth).
=> Add option to pass client credentials in request body

pkg/types/broker.go
This pull request https://github.com/Peripli/service-manager/pull/223 introduces a breaking change. The CLI needs to be adapted so that `list-brokers` command behaves properly.
The `types.Brokers` struct's tag is update with accordance to the response body of the `/v1/service_brokers` endpoint.
=> Update Brokers struct tag

Gopkg.toml, internal/cmd/broker/list_brokers_test.go, internal/cmd/curl/curl_test.go, internal/cmd/offering/list_offerings.go, internal/cmd/offering/list_offerings_test.go, internal/cmd/platform/list_platforms_test.go, main.go, pkg/smclient/client.go, pkg/smclient/client_test.go, pkg/smclient/smclientfakes/fake_client.go, pkg/types/service_offering.go, pkg/types/service_plan.go
Service Manager provides APIs for listing Service Offerings and Plans so the cli should be adapted.
Introduced smctl list-offerings (smctl lo) command for listing service offerings and --service (-s) flag for detailed view of the offering's plans.
=> Add commands for listing service offerings and plans.

Gopkg.lock, Gopkg.toml, internal/cmd/broker/list_brokers_test.go, internal/cmd/offering/list_offerings_test.go, internal/cmd/platform/delete_platform.go, internal/cmd/platform/register_platform_test.go, internal/cmd/visibility/delete_visibility.go, internal/cmd/visibility/delete_visibility_test.go, internal/cmd/visibility/list_visibilities.go, internal/cmd/visibility/list_visibilities_test.go, internal/cmd/visibility/register_visibility.go, internal/cmd/visibility/register_visibility_test.go, internal/cmd/visibility/update_visibility.go, internal/cmd/visibility/update_visibility_test.go, main.go, pkg/smclient/client.go, pkg/smclient/client_test.go, pkg/smclient/smclientfakes/fake_client.go, pkg/types/broker.go, pkg/types/platform.go, pkg/types/service_plan.go, pkg/types/visibility.go
Service Manager CLI does not support commands for managing plan visibilities.
Introduced 4 new commands:
`smctl list-visibilities`
`smctl register-visibility`
`smctl delete-visibility`
`smctl update-visibility`
=> SMCLI commands for managing plan visibilities.

internal/cmd/broker/delete_broker.go, internal/cmd/broker/delete_broker_test.go, internal/cmd/broker/update_broker.go, internal/cmd/broker/update_broker_test.go, internal/cmd/platform/delete_platform.go, internal/cmd/platform/delete_platform_test.go, internal/cmd/platform/update_platform.go, internal/cmd/platform/update_platform_test.go, internal/util/util.go, pkg/smclient/client.go, pkg/smclient/smclientfakes/fake_client.go, pkg/types/platform.go
SMCLI commands for update and delete platforms and brokers was developed before field querying.
Since field querying was introduces there is better solution for this commands and refactoring was needed.
Update and delete commands work with names, and SM update and delete APIs work with IDs.
Before the approach was to list all brokers and then iterate over to find that brokers with names given for deletion. With field querying this could be achieved in a single call to SM.
=> Field querying on update and delete commands

Gopkg.lock, internal/cmd/label/label.go, internal/cmd/label/label_test.go, main.go, pkg/smclient/client.go, pkg/smclient/client_test.go, pkg/smclient/smclientfakes/fake_client.go, pkg/types/label_changes.go
SM supports labels on resources but the CLI does not support labeling.
This PR introduces new command for labeling resources.
`smctl label [resource] [id] [operation] [key=value1,value2,...] `
Where for now resource is one of the following:
- platform
- broker
And supported operations are:
- add
- remove
- add-values
- remove-values
=> Label command for resource labeling

internal/cmd/broker/delete_broker.go, internal/cmd/broker/delete_broker_test.go, internal/cmd/platform/delete_platform.go, internal/cmd/platform/delete_platform_test.go
SM CLI returns error when all resources given for deletion are not found. This must not be considered as a failed command.
Check if the response is 404 Not Found and print appropriate message, but not fail the command with and error.
=> Error handling on delete operations

.travis.yml
Travis build job times out if there is no output for 10m
This happens sometimes during `dep ensure`
=> Run dep ensure with -v to prevent build job timeout

README.md
The current manual installation guide is outdated.
https://github.com/Peripli/service-manager-cli/issues/52
Updated the manual installation guide.
=> Fix manual installation guide

Gopkg.lock, Gopkg.toml, docs/commands/login.md, docs/commands/register-broker.md, internal/cmd/instance/list_instances.go, internal/cmd/instance/list_instances_test.go, main.go, pkg/smclient/client.go, pkg/smclient/client_test.go, pkg/smclient/smclientfakes/fake_client.go, pkg/types/service_instance.go
Service Manager provides API for listing Service Instances so the cli should be adapted.
Introduced smctl list-instances (smctl li) command for listing service instances. Field, label and general query is supported as well.
=> Introduce list service instances command

internal/cmd/commander.go
This implies inconsistency in the CLI behaviour and thus makes it impossible to be used programatically.
=> Remove silent poll in async commands

internal/cmd/commander.go, internal/cmd/context.go, internal/cmd/login/login.go, internal/cmd/smctl.go, main.go, pkg/smclient/client.go, pkg/smclient/test/binding_test.go, pkg/smclient/test/broker_test.go, pkg/smclient/test/client_test.go, pkg/smclient/test/instance_test.go, pkg/smclient/test/label_test.go, pkg/smclient/test/platform_test.go, pkg/smclient/test/smclient_suite_test.go, pkg/smclient/test/visibility_test.go
Previously `-v --verbose` flag was not doing anything. With this change the `-v` flag prints all calls to SM.
```
smctl get-broker test-broker-subacc-cfdev-tenant-id -v
DEBU[0000] Sending request GET http://localhost:8081/v1/service_brokers?fieldQuery=name+eq+%27test-broker-subacc-cfdev-tenant-id%27  component="util/client.go:87" correlation_id=-
DEBU[0000] Sending request GET http://localhost:8081/v1/service_brokers/507ba725-7554-4ead-b870-bb56cece92ad  component="smclient/client.go:467" correlation_id=-
| ID           | 507ba725-7554-4ead-b870-bb56cece92ad  |
| Name         | test-broker-subacc-cfdev-tenant-id    |
| URL          | http://sm-test-broker:8083            |
| Description  | asd                                   |
| Created      | 2020-04-06T13:06:26.965654Z           |
| …
```
=> Improve verobse output

.gitignore, internal/cmd/instance/deprovision_test.go, internal/cmd/instance/transfer.go, internal/cmd/instance/transfer_test.go, main.go, pkg/smclient/client.go, pkg/smclient/smclientfakes/fake_client.go, pkg/smclient/test/instance_test.go
Transfer instance command is a command for easier usage of updating a service instance and transferring it to another platform
=> Implement transfer-instance command

pkg/smclient/client.go
the SM client NewClientWithAuth function created an invalid client without context, this seems to have been missed in one of the last refactorings.
=> create context in NewClientWithAuth

Gopkg.toml, docs/commands/get-binding.md, docs/commands/get-instance.md, internal/cmd/binding/get_binding.go, internal/cmd/binding/get_binding_test.go, internal/cmd/instance/get_instance.go, internal/cmd/instance/get_instance_test.go, internal/output/output.go, pkg/smclient/client.go, pkg/smclient/smclientfakes/fake_client.go, pkg/smclient/test/binding_test.go, pkg/smclient/test/instance_test.go, pkg/smclient/test/smclient_suite_test.go
In many cases services require input parameters for service instances or service bindings creation. These parameters are used by the broker in the provisioning process.
This information is valuable to the instance owner and might be required in order to manage the instance.
Currently service manager does not store this information and thus it cannot be retrieved.
BLI: https://jtrack.wdf.sap.corp/browse/SAPCPCFS-17437?src=confmacro
Use checklists as a means to represent the status of your Pull Request.
For example:
=> Retrieve instance Parameters of service instances and bindings

docs/commands/update-broker.md, internal/cmd/broker/update_broker.go
The update only works with broker_url. The parameter broker-url does not work.
Closes #78 
Wrong Documentation
Correct documentation
See also [SM API documentation](https://github.com/Peripli/specification/blob/master/api.md#request-body-2), which uses broker_url
=> [WIP] Fix update broker documentation (broker_url parameter)

internal/cmd/binding/bind.go, internal/cmd/binding/get_binding.go, internal/cmd/binding/unbind.go, internal/cmd/broker/delete_broker.go, internal/cmd/broker/get_broker.go, internal/cmd/broker/update_broker.go, internal/cmd/instance/deprovision.go, internal/cmd/instance/get_instance.go, internal/cmd/instance/provision.go, internal/cmd/instance/transfer.go
When passing parameters with `--param` those parameters should be sent with every request to service-manager. In some of the flows requests made to fetch data before the operation ignored them, this change is adding them there as well.
=> propagate params in all requests to SM

internal/cmd/binding/get_binding.go, internal/cmd/binding/list_bindings.go
Fix 2 binding commands that I missed in https://github.com/Peripli/service-manager-cli/pull/86
=> propagate params to SM in binding commands

Gopkg.lock, Gopkg.toml, docs/commands/delete-platform.md, internal/cmd/binding/get_binding_test.go, internal/cmd/instance/get_instance_test.go, internal/cmd/platform/delete_platform.go, internal/cmd/platform/delete_platform_test.go, pkg/smclient/client.go, pkg/smclient/smclientfakes/fake_client.go, pkg/smclient/test/platform_test.go
Cleanup service instances and binding on platform unregistration
In cases where subaccount scoped platform is not reachable (e.g. K8S cluster was deleted) and service instances and bindings were not properly deleted, brokers are not notified and resources were not deallocated, which may lead resource exhaustion and unnecessary costs. 
The goal of this user story is to enhance the unregisteration flow of SA scoped platform to allow structured cleanup of its resources and avoid waste of resources and money.
https://jtrack.wdf.sap.corp/browse/SAPCPCFS-17435
Use checklists as a means to represent the status of your Pull Request.
For example:
=> Platform cascade delete

pkg/types/service_plan.go
Use instance_sharing.SupportsInstanceSharingKey instead of a string of the key.
=> use const instance_sharing.SupportsInstanceSharingKey

.github/workflows/release.yml
added support for Linux Arm64 arch.
Proposing a solution for this
https://github.com/Peripli/service-manager-cli/issues/163
On Mac M1 machines, users run their development environment in docker containers. Building Docker containers on M1 machines result in using Linux on ARM. Running smctl amd64 binaries result in errors
i added in the release yaml support to linux arm64
=> Added support for Linux ARM64
